### ISSUE TITLE
outputport.close does not return promise

### ISSUE THREAD

**Issue by Raynos** [Gozala/streams#14]
it would be nice if `port.close` returns a promise when its done completing all pending puts / takes.

**Comment by Gozala** [comment]
As far as I know CSP does not provides any notifications for this, likely because close does not block. It also only make sense to from the producer side, as consumer doing a close already has a way to know when the close is complete. On the other hand producer also can observe last put to know that.

May I ask what would be a use case ?

**Comment by Raynos** [comment]
the use case was porting the whatwg/streams examples literally.

I'll re-open this issue when i have a real use case.
